export const syllableRe = /^([bchgjklmnpst]*)([aeiouwo̤ṳ]*)([hpkmngtⁿ]*)$/;

export const initialToPuj = {
  ""   : ""    ,
  "b"  : "b"   ,
  "c"  : "ts"  ,
  "ch" : "tsh" ,
  "g"  : "g"   ,
  "h"  : "h"   ,
  "j"  : "j"   ,
  "k"  : "k"   ,
  "kh" : "kh"  ,
  "l"  : "l"   ,
  "m"  : "m"   ,
  "n"  : "n"   ,
  "ng" : "ng"  ,
  "p"  : "p"   ,
  "ph" : "ph"  ,
  "s"  : "s"   ,
  "t"  : "t"   ,
  "th" : "th"
}

export const finalToPuj = {
  ""     : [ "", "" ],
  "a"    : [ "a", "" ],
  "ah"   : [ "a", "h" ],
  "ai"   : [ "ai", "" ],
  "aih"  : [ "ai", "h" ],
  "aiⁿ"  : [ "ai", "ⁿ" ],
  "ak"   : [ "a", "k" ],
  "am"   : [ "a", "m" ],
  "an"   : [ "a", "n" ],
  "ang"  : [ "a", "ng" ],
  "ap"   : [ "a", "p" ],
  "at"   : [ "a", "t" ],
  "au"   : [ "au", "" ],
  "auh"  : [ "au", "h" ],
  "auⁿ"  : [ "au", "ⁿ" ],
  "aⁿ"   : [ "a", "ⁿ" ],
  "e"    : [ "e", "" ],
  "eh"   : [ "e", "h" ],
  "ehⁿ"  : [ "e", "ⁿh" ],
  "ek"   : [ "e", "k" ],
  "eng"  : [ "e", "ng" ],
  "eⁿ"   : [ "e", "ⁿ" ],
  "ng"   : [ "" , "ng" ],
  "i"    : [ "i", "" ],
  "ia"   : [ "ia", "" ],
  "iah"  : [ "ia", "h" ],
  "iak"  : [ "ia", "k" ],
  "iam"  : [ "ia", "m" ],
  "iang" : [ "ia", "ng" ],
  "iap"  : [ "ia", "p" ],
  "iaⁿ"  : [ "ia", "ⁿ" ],
  "ie"   : [ "ie", "" ],
  "ieh"  : [ "ie", "h" ],
  "ien"  : [ "ie", "n" ],
  "iet"  : [ "ie", "t" ],
  "ieⁿ"  : [ "ie", "ⁿ" ],
  "ih"   : [ "i", "h" ],
  "im"   : [ "i", "m" ],
  "in"   : [ "i", "n" ],
  "ing"  : [ "i", "ng" ], // Not in Fielde
  "io"   : [ "iou", "" ],
  "ioh"  : [ "io", "h" ],
  "iohⁿ" : [ "io", "ⁿh" ],
  "iok"  : [ "io", "k" ],
  "iong" : [ "io", "ng" ],
  "ioⁿ"  : [ "iou", "ⁿ" ],
  "ip"   : [ "i", "p" ],
  "it"   : [ "i", "t" ],
  "iu"   : [ "iu", "" ],
  "iuh"  : [ "iu", "h" ],
  "iuⁿ"  : [ "iu", "ⁿ" ],
  "iⁿ"   : [ "i", "ⁿ" ],
  "ngk"  : [ "" , "ngk" ],
  "m"    : [ "", "m" ],
  "o"    : [ "ou", "" ],
  "oa"   : [ "ua", "" ],   // Not distinguished in PUJ
  "oah"  : [ "ua", "h" ],  // Not distinguished in PUJ
  "oaⁿ"  : [ "ua", "ⁿ" ],  // Not distinguished in PUJ
  "oi"   : [ "oi", "" ],
  "oih"  : [ "oi", "h" ],
  "oiⁿ"  : [ "oi", "ⁿ" ],
  "ok"   : [ "o", "k" ],
  "ong"  : [ "o", "ng" ],
  "o̤"    : [ "o", "" ],
  "o̤h"   : [ "o", "h" ],
  "o̤ⁿ"   : [ "o", "ⁿ" ],
  "oⁿ"   : [ "ou", "ⁿ" ],
  "u"    : [ "u", "" ],
  "ua"   : [ "ua", "" ],
  "uah"  : [ "ua", "h" ],
  "uai"  : [ "uai", "" ],
  "uaihⁿ": [ "uai", "ⁿh" ],
  "uaiⁿ" : [ "uai", "ⁿ" ],
  "uak"  : [ "ua", "k" ],
  "uam"  : [ "ua", "m" ],
  "uang" : [ "ua", "ng" ],
  "uap"  : [ "ua", "p" ],
  "uaⁿ"  : [ "ua", "ⁿ" ],
  "ue"   : [ "ue", "" ],
  "ueh"  : [ "ue", "h" ],
  "ueⁿ"  : [ "ue", "ⁿ" ],
  "uh"   : [ "u", "h" ],
  "ui"   : [ "ui", "" ],
  "uih"  : [ "ui", "h" ],
  "uiⁿ"  : [ "ui", "ⁿ" ],
  "un"   : [ "u", "n" ],
  "ut"   : [ "u", "t" ],
  "ṳ"    : [ "ṳ", "" ],
  "ṳh"   : [ "ṳ", "h" ],
  "ṳn"   : [ "ṳ", "n" ],
  "ṳt"   : [ "ṳ", "t" ],
  "wn"   : [ "ue", "n" ],
  "wt"   : [ "ue", "t" ]
}

export const initialFromPuj = {
  ""    : ""   ,
  "b"   : "b"  ,
  "ts"  : "c"  ,
  "tsh" : "ch" ,
  "g"   : "g"  ,
  "h"   : "h"  ,
  "j"   : "j"  ,
  "k"   : "k"  ,
  "kh"  : "kh" ,
  "l"   : "l"  ,
  "m"   : "m"  ,
  "n"   : "n"  ,
  "ng"  : "ng" ,
  "p"   : "p"  ,
  "ph"  : "ph" ,
  "s"   : "s"  ,
  "t"   : "t"  ,
  "th"  : "th" 
}


// export const finalFromPuj = {
//   [ "a", "" ]    : "a"    ,
//   [ "a", "h" ]   : "ah"   ,
//   [ "ai", "" ]   : "ai"   ,
//   [ "ai", "h" ]  : "aih"  ,
//   [ "ai", "ⁿ" ]  : "aiⁿ"  ,
//   [ "a", "k" ]   : "ak"   ,
//   [ "a", "m" ]   : "am"   ,
//   [ "a", "n" ]   : "an"   ,
//   [ "a", "ng" ]  : "ang"  ,
//   [ "a", "p" ]   : "ap"   ,
//   [ "a", "t" ]   : "at"   ,
//   [ "au", "" ]   : "au"   ,
//   [ "au", "h" ]  : "auh"  ,
//   [ "au", "ⁿ" ]  : "auⁿ"  ,
//   [ "a", "ⁿ" ]   : "aⁿ"   ,
//   [ "e", "" ]    : "e"    ,
//   [ "e", "h" ]   : "eh"   ,
//   [ "e", "ⁿh" ]  : "ehⁿ"  ,
//   [ "e", "k" ]   : "ek"   ,
//   [ "e", "ng" ]  : "eng"  ,
//   [ "e", "ⁿ" ]   : "eⁿ"   ,
//   [ "" , "ng" ]  : "ng"   ,
//   [ "i", "" ]    : "i"    ,
//   [ "ia", "" ]   : "ia"   ,
//   [ "ia", "h" ]  : "iah"  ,
//   [ "ia", "k" ]  : "iak"  ,
//   [ "ia", "m" ]  : "iam"  ,
//   [ "ia", "ng" ] : "iang" ,
//   [ "ia", "p" ]  : "iap"  ,
//   [ "ia", "ⁿ" ]  : "iaⁿ"  ,
//   [ "iau", "" ]  : "iau"  , // Not in Fielde
//   [ "iau", "ⁿ" ] : "iauⁿ" , // Not in Fielde
//   [ "ie", "" ]   : "ie"   ,
//   [ "ie", "h" ]  : "ieh"  ,
//   [ "ie", "n" ]  : "ien"  ,
//   [ "ie", "t" ]  : "iet"  ,
//   [ "ie", "ⁿ" ]  : "ieⁿ"  ,
//   [ "i", "h" ]   : "ih"   ,
//   [ "i", "m" ]   : "im"   ,
//   [ "i", "n" ]   : "in"   ,
//   [ "i", "ng" ]  : "ing"  , // Not in Fielde
//   [ "io", "" ]   : "io̤"   , // Not in Fielde
//   [ "io", "n" ]  : "io̤ⁿ"  , // Not in Fielde
//   [ "iou", "" ]  : "io"   ,
//   [ "io", "h" ]  : "ioh"  ,
//   [ "io", "ⁿh" ] : "iohⁿ" ,
//   [ "io", "k" ]  : "iok"  ,
//   [ "io", "ng" ] : "iong" ,
//   [ "iou", "ⁿ" ] : "ioⁿ"  ,
//   [ "i", "p" ]   : "ip"   ,
//   [ "i", "t" ]   : "it"   ,
//   [ "iu", "" ]   : "iu"   ,
//   [ "iu", "h" ]  : "iuh"  ,
//   [ "iu", "ⁿ" ]  : "iuⁿ"  ,
//   [ "i", "ⁿ" ]   : "iⁿ"   ,
//   [ "" , "ngk" ] : "ngk"  ,
//   [ "", "m" ]    : "m"    ,
//   [ "ou", "" ]   : "o"    ,
//   [ "oi", "" ]   : "oi"   ,
//   [ "oi", "h" ]  : "oih"  ,
//   [ "oi", "ⁿ" ]  : "oiⁿ"  ,
//   [ "o", "k" ]   : "ok"   ,
//   [ "o", "ng" ]  : "ong"  ,
//   [ "o", "" ]    : "o̤"    ,
//   [ "o", "h" ]   : "o̤h"   ,
//   [ "o", "ⁿ" ]   : "o̤ⁿ"   ,
//   [ "ou", "ⁿ" ]  : "oⁿ"   ,
//   [ "u", "" ]    : "u"    ,
//   [ "ua", "" ]   : "ua"   ,
//   [ "ua", "h" ]  : "uah"  ,
//   [ "uai", "" ]  : "uai"  ,
//   [ "uai", "ⁿh" ]: "uaihⁿ",
//   [ "uai", "ⁿ" ] : "uaiⁿ" ,
//   [ "ua", "k" ]  : "uak"  ,
//   [ "ua", "m" ]  : "uam"  ,
//   [ "ua", "ng" ] : "uang" ,
//   [ "ua", "p" ]  : "uap"  ,
//   [ "ua", "ⁿ" ]  : "uaⁿ"  ,
//   [ "ue", "" ]   : "ue"   ,
//   [ "ue", "h" ]  : "ueh"  ,
//   [ "ue", "ⁿ" ]  : "ueⁿ"  ,
//   [ "u", "h" ]   : "uh"   ,
//   [ "ui", "" ]   : "ui"   ,
//   [ "ui", "h" ]  : "uih"  ,
//   [ "ui", "ⁿ" ]  : "uiⁿ"  ,
//   [ "u", "n" ]   : "un"   ,
//   [ "u", "t" ]   : "ut"   ,
//   [ "ṳ", "" ]    : "ṳ"    ,
//   [ "ṳ", "h" ]   : "ṳh"   ,
//   [ "ṳ", "n" ]   : "ṳn"   ,
//   [ "ṳ", "t" ]   : "ṳt"   ,
//   [ "ue", "n" ]  : "wn"   ,
//   [ "ue", "ng" ] : "wng"  , // not in Fielde
//   [ "ue", "t" ]  : "wt"   
// }
