export const syllableRe = /^([bchgjklmnpst]*)([aeiouwo̤ṳ]*)([hpkmngtⁿ]*)$/;

export const initialToPuj = {
  ""   : ""    ,
  "b"  : "b"   ,
  "c"  : "ts"  ,
  "ch" : "tsh" ,
  "g"  : "g"   ,
  "h"  : "h"   ,
  "j"  : "j"   ,
  "k"  : "k"   ,
  "kh" : "kh"  ,
  "l"  : "l"   ,
  "m"  : "m"   ,
  "n"  : "n"   ,
  "ng" : "ng"  ,
  "p"  : "p"   ,
  "ph" : "ph"  ,
  "s"  : "s"   ,
  "t"  : "t"   ,
  "th" : "th"
}

export const finalToPuj = {
  ""     : [ "", "" ],
  "a"    : [ "a", "" ],
  "ah"   : [ "a", "h" ],
  "ai"   : [ "ai", "" ],
  "aih"  : [ "ai", "h" ],
  "aiⁿ"  : [ "ai", "ⁿ" ],
  "ak"   : [ "a", "k" ],
  "am"   : [ "a", "m" ],
  "an"   : [ "a", "n" ],
  "ang"  : [ "a", "ng" ],
  "ap"   : [ "a", "p" ],
  "at"   : [ "a", "t" ],
  "au"   : [ "au", "" ],
  "auh"  : [ "au", "h" ],
  "auⁿ"  : [ "au", "ⁿ" ],
  "aⁿ"   : [ "a", "ⁿ" ],
  "e"    : [ "e", "" ],
  "eh"   : [ "e", "h" ],
  "ehⁿ"  : [ "e", "ⁿh" ],
  "ek"   : [ "e", "k" ],
  "eng"  : [ "e", "ng" ],
  "eⁿ"   : [ "e", "ⁿ" ],
  "ng"   : [ "" , "ng" ],
  "i"    : [ "i", "" ],
  "ia"   : [ "ia", "" ],
  "iah"  : [ "ia", "h" ],
  "iak"  : [ "ia", "k" ],
  "iam"  : [ "ia", "m" ],
  "iang" : [ "ia", "ng" ],
  "iap"  : [ "ia", "p" ],
  "iaⁿ"  : [ "ia", "ⁿ" ],
  "ie"   : [ "ie", "" ],
  "ieh"  : [ "ie", "h" ],
  "ien"  : [ "ie", "n" ],
  "iet"  : [ "ie", "t" ],
  "ieⁿ"  : [ "ie", "ⁿ" ],
  "ih"   : [ "i", "h" ],
  "im"   : [ "i", "m" ],
  "in"   : [ "i", "n" ],
  "ing"  : [ "i", "ng" ], // Not in Fielde
  "io"   : [ "iou", "" ],
  "ioh"  : [ "io", "h" ],
  "iohⁿ" : [ "io", "ⁿh" ],
  "iok"  : [ "io", "k" ],
  "iong" : [ "io", "ng" ],
  "ioⁿ"  : [ "iou", "ⁿ" ],
  "ip"   : [ "i", "p" ],
  "it"   : [ "i", "t" ],
  "iu"   : [ "iu", "" ],
  "iuh"  : [ "iu", "h" ],
  "iuⁿ"  : [ "iu", "ⁿ" ],
  "iⁿ"   : [ "i", "ⁿ" ],
  "ngk"  : [ "" , "ngk" ],
  "m"    : [ "", "m" ],
  "o"    : [ "ou", "" ],
  "oa"   : [ "ua", "" ],   // Not distinguished in PUJ
  "oah"  : [ "ua", "h" ],  // Not distinguished in PUJ
  "oaⁿ"  : [ "ua", "ⁿ" ],  // Not distinguished in PUJ
  "oi"   : [ "oi", "" ],
  "oih"  : [ "oi", "h" ],
  "oiⁿ"  : [ "oi", "ⁿ" ],
  "ok"   : [ "o", "k" ],
  "ong"  : [ "o", "ng" ],
  "o̤"    : [ "o", "" ],
  "o̤h"   : [ "o", "h" ],
  "o̤ⁿ"   : [ "o", "ⁿ" ],
  "oⁿ"   : [ "ou", "ⁿ" ],
  "u"    : [ "u", "" ],
  "ua"   : [ "ua", "" ],
  "uah"  : [ "ua", "h" ],
  "uai"  : [ "uai", "" ],
  "uaihⁿ": [ "uai", "ⁿh" ],
  "uaiⁿ" : [ "uai", "ⁿ" ],
  "uak"  : [ "ua", "k" ],
  "uam"  : [ "ua", "m" ],
  "uang" : [ "ua", "ng" ],
  "uap"  : [ "ua", "p" ],
  "uaⁿ"  : [ "ua", "ⁿ" ],
  "ue"   : [ "ue", "" ],
  "ueh"  : [ "ue", "h" ],
  "ueⁿ"  : [ "ue", "ⁿ" ],
  "uh"   : [ "u", "h" ],
  "ui"   : [ "ui", "" ],
  "uih"  : [ "ui", "h" ],
  "uiⁿ"  : [ "ui", "ⁿ" ],
  "un"   : [ "u", "n" ],
  "ut"   : [ "u", "t" ],
  "ṳ"    : [ "ṳ", "" ],
  "ṳh"   : [ "ṳ", "h" ],
  "ṳn"   : [ "ṳ", "n" ],
  "ṳt"   : [ "ṳ", "t" ],
  "wn"   : [ "ue", "n" ],
  "wt"   : [ "ue", "t" ]
}

export const initialFromPuj = {
  ""    : ""   ,
  "b"   : "b"  ,
  "ts"  : "c"  ,
  "tsh" : "ch" ,
  "ch"  : "c"  , // Fielde does not distinguish
  "chh" : "ch" , // Fielde does not distinguish
  "g"   : "g"  ,
  "h"   : "h"  ,
  "j"   : "j"  ,
  "k"   : "k"  ,
  "kh"  : "kh" ,
  "l"   : "l"  ,
  "m"   : "m"  ,
  "n"   : "n"  ,
  "ng"  : "ng" ,
  "p"   : "p"  ,
  "ph"  : "ph" ,
  "s"   : "s"  ,
  "t"   : "t"  ,
  "th"  : "th" 
}

export const finalFromPuj = {
  "a"    : "a"    ,
  "ah"   : "ah"   ,
  "ai"   : "ai"   ,
  "aih"  : "aih"  ,
  "aiⁿ"  : "aiⁿ"  ,
  "ak"   : "ak"   ,
  "am"   : "am"   ,
  "an"   : "an"   ,
  "ang"  : "ang"  ,
  "ap"   : "ap"   ,
  "at"   : "at"   ,
  "au"   : "au"   ,
  "auh"  : "auh"  ,
  "auⁿ"  : "auⁿ"  ,
  "aⁿ"   : "aⁿ"   ,
  "e"    : "e"    ,
  "eh"   : "eh"   ,
  "eⁿh"  : "ehⁿ"  ,
  "ek"   : "ek"   ,
  "eng"  : "eng"  ,
  "eⁿ"   : "eⁿ"   ,
  "ng"   : "ng"   ,
  "ngh"  : "ngh"  , // Not in Fielde
  "i"    : "i"    ,
  "ia"   : "ia"   ,
  "iah"  : "iah"  ,
  "iak"  : "iak"  ,
  "iam"  : "iam"  ,
  "iang" : "iang" ,
  "iap"  : "iap"  ,
  "iaⁿ"  : "iaⁿ"  ,
  "iau"  : "iau"  , // Not in Fielde
  "iauⁿ" : "iauⁿ" , // Not in Fielde
  "ie"   : "ie"   ,
  "ieh"  : "ieh"  ,
  "ien"  : "ien"  ,
  "iet"  : "iet"  ,
  "ieⁿ"  : "ieⁿ"  ,
  "ih"   : "ih"   ,
  "im"   : "im"   ,
  "in"   : "in"   ,
  "ing"  : "ing"  , // Not in Fielde
  "io"   : "io̤"   , // Not in Fielde
  "ion"  : "io̤ⁿ"  , // Not in Fielde
  "iou"  : "io"   ,
  "ioh"  : "ioh"  ,
  "ioⁿh" : "iohⁿ" ,
  "iok"  : "iok"  ,
  "iong" : "iong" ,
  "iouⁿ" : "ioⁿ"  ,
  "ip"   : "ip"   ,
  "it"   : "it"   ,
  "iu"   : "iu"   ,
  "iuh"  : "iuh"  ,
  "iuⁿ"  : "iuⁿ"  ,
  "iⁿ"   : "iⁿ"   ,
  "ngk" : "ngk"  ,
  "m"    : "m"    ,
  "ou"   : "o"    ,
  "oi"   : "oi"   ,
  "oih"  : "oih"  ,
  "oiⁿ"  : "oiⁿ"  ,
  "ok"   : "ok"   ,
  "ong"  : "ong"  ,
  "o"    : "o̤"    ,
  "oh"   : "o̤h"   ,
  "oⁿ"   : "o̤ⁿ"   ,
  "ouⁿ"  : "oⁿ"   ,
  "u"    : "u"    ,
  "ua"   : "ua"   ,
  "uah"  : "uah"  ,
  "uai"  : "uai"  ,
  "uaiⁿh": "uaihⁿ",
  "uaiⁿ" : "uaiⁿ" ,
  "uak"  : "uak"  ,
  "uam"  : "uam"  ,
  "uang" : "uang" ,
  "uap"  : "uap"  ,
  "uaⁿ"  : "uaⁿ"  ,
  "ue"   : "ue"   ,
  "ueh"  : "ueh"  ,
  "ueⁿ"  : "ueⁿ"  ,
  "uh"   : "uh"   ,
  "ui"   : "ui"   ,
  "uih"  : "uih"  ,
  "uiⁿ"  : "uiⁿ"  ,
  "un"   : "un"   ,
  "ut"   : "ut"   ,
  "ṳ"    : "ṳ"    ,
  "ṳh"   : "ṳh"   ,
  "ṳn"   : "ṳn"   ,
  "ṳt"   : "ṳt"   ,
  "uen"  : "wn"   ,
  "ueng" : "wng"  , // not in Fielde
  "uet"  : "wt"
}
